---
title: A Step-by-Step Guide for Research Design
---

Coming up with a good research question and design is not a simple process. For this reason, you may do some of the things discussed here in a different order.


# Step 1: Develop a Research Question

This may perhaps the most difficult step in the research process and one where guidance is also the most difficult to provide. For our current purposes, let's assume you have a question. Let's use the following one as an example:

- Does being religious make an individual more likely to vote?

This is a similar question to one that scholars interested on the intersection of religion and politics have asked (albeit a bit differently).

Once you have a research question, make sure you can identify:
1. The outcome of interest (conceptually, you don't need to measure yet)
2. The explanatory concept (how are you trying to explain a change in the outcome? What's having an effect on the outcome?)

In this example, the answers are (1) turning out to vote and (2) being religious


# Step 2










